### ISSUE TITLE
 Cannot play this video! (YouTube)

### ISSUE THREAD

**Issue by lewe2k6** [JavaDevMC/Discord-YouTube-Stream#1]
I have installed ytdl-core, discord.js-selfbot-v13, googleapis, puppeteer-stream, puppeteer, axios, @dank074/discord-video-stream
when using _$play <yt-link>_ it keeps saying _Cannot play this video!_

> sorry for my bad english

**Comment by maximjsx** [comment]
Try a different video because i also had problems with some videos... also look in the console there should be an error message.

**Comment by maximjsx** [comment]
To fix bugs like that and for a better quality ig i will implement a downloader to play the video from a local file instead of streaming it.
